# Generated by Django 5.0.6 on 2024-08-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
    ]
