# Generated by Django 5.0.6 on 2024-08-12 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_area_icon'),
        ('visitors', '0002_alter_schoolgroup_group'),
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.area'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='school_group',
            field=models.ManyToManyField(to='visitors.schoolgroup'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Vyber ze 2 možností'), (2, 'Vyber správnou možnost'), (3, 'Vyber správnou možnost s obrázkem'), (4, 'Obrázek s čísly'), (5, 'Spoj dvojice')], default=1),
        ),
    ]
