# Generated by Django 5.0.9 on 2024-10-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_area_icon'),
        ('worksheets', '0003_remove_task_type_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheet',
            old_name='school_group',
            new_name='school_groups',
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.area'),
        ),
    ]
