# Generated by Django 5.0.9 on 2024-10-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0004_rename_school_group_worksheet_school_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
