# Generated by Django 5.0.3 on 2024-03-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(blank=True, choices=[(1, 'Mateřská škola'), (2, 'První stupeň základní školy'), (3, 'Druhý stupeň základní školy / Nižší stupeň gymnázia'), (4, 'Střední škola / Vyšší stupeň gymnázia')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('worksheets', models.ManyToManyField(to='worksheets.worksheet')),
                ('school_group', models.ManyToManyField(to='visitors.schoolgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('achievements', models.ManyToManyField(to='visitors.achievement')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitors.school')),
                ('school_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitors.schoolgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField()),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.worksheet')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.question')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
        ),
    ]
