# Generated by Django 5.0.6 on 2024-08-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgroup',
            name='group',
            field=models.IntegerField(choices=[(1, 'Mateřská škola'), (2, 'První stupeň základní školy'), (3, 'Druhý stupeň základní školy / Nižší stupeň gymnázia'), (4, 'Střední škola / Vyšší stupeň gymnázia')], default=2),
        ),
    ]
