# Generated by Django 5.1.4 on 2025-01-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_rename_school_group_school_school_groups_and_more'),
        ('worksheets', '0007_alter_taskimage_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorresponse',
            name='option',
        ),
        migrations.AddField(
            model_name='visitor',
            name='username',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorresponse',
            name='options',
            field=models.ManyToManyField(to='worksheets.option'),
        ),
    ]
