# Generated by Django 5.1.4 on 2025-01-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_remove_visitorresponse_option_visitor_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='school_group',
        ),
        migrations.AddField(
            model_name='visitor',
            name='school_group',
            field=models.ManyToManyField(to='visitors.schoolgroup'),
        ),
    ]
