# Generated by Django 5.1.4 on 2025-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_remove_visitor_school_group_visitor_school_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
