# Generated by Django 5.1.4 on 2025-01-31 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_successrate_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='school',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='username',
        ),
        migrations.AddField(
            model_name='visitorresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
