# Generated by Django 5.1.4 on 2025-03-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_remove_visitor_school_remove_visitor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='achievements',
        ),
        migrations.AddField(
            model_name='visitor',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
